adobe/NLP-Cube

examples/lemmatizer.conf, examples/parser.conf, examples/tagger.conf, examples/tokenizer.conf
=> Added new style conf examples

.gitignore, cube/.idea/cube.iml, cube/.idea/misc.xml, cube/generic_networks/token_expanders.py, cube/generic_networks/tokenizers.py, cube/io_utils/config.py, cube/io_utils/encodings.py, cube/io_utils/trainers.py, cube/main.py, cube/server/webserver.py
I have modified the tokenizer to perform sentence splitting and tokenization in two separate steps. Sentence accuracy on ZH is now 90.09% and token accuracy has passed 93%
Also I added a compound word expander which works separately from the tokenizer
=> Enhancement.tokenizer

cube/generic_networks/lemmatizers.py, cube/io_utils/config.py, cube/io_utils/trainers.py, cube/main.py, cube/server/webserver.py
Implemented and tested a new FST-based architecture for the lemmatizer. It does not require an attention mechanism and achieves 96% accuracy on the Romanian UD Dataset (versus 93% - the old encoder-decoder architecture)
Closes #11
=> Enhancement.fst lemmatizer

cube/generic_networks/token_expanders.py, cube/generic_networks/tokenizers.py
This PR solves a problem in tokenizer training. The previous version merged each two consecutive sentences into a single training example which was deferring from the actual runtime process, hence the poor performance on the real data.
Closes #15
=> Bug.tokenizer

cube/generic_networks/taggers.py, cube/io_utils/trainers.py
Added batching support for tagger. 
Closes #21
=> Implemented batching for tagger.

cube/generic_networks/taggers.py, cube/io_utils/trainers.py, cube/main.py
=> Feature.tagger batch

cube/generic_networks/parsers.py, cube/io_utils/config.py, cube/main.py
Finished update to allow non-lexicalized parsing.
=> Delexicalized parser

cube/generic_networks/lemmatizers.py, cube/generic_networks/parsers.py, cube/generic_networks/taggers.py, cube/generic_networks/token_expanders.py, cube/io_utils/config.py, cube/io_utils/conll.py, cube/io_utils/embeddings.py, cube/io_utils/encodings.py, cube/io_utils/trainers.py, cube/main.py, cube/misc/conll18_ud_eval_wrapper.py
Integration of end-2-end functionality by running --run [pipeline]. Also added conll18 eval wrapper.
=> End2end functionality

cube/generic_networks/tokenizers.py, cube/io_utils/trainers.py, cube/main.py
Corrected behaviour for languages that have multiple blank lines and that treat those as hard sentence delimiter
=> tokenizer eval now tokenizes paragraphs separately

cube/io_utils/encodings.py
=> corrected encodings

.gitignore, requirements.txt, setup.py
=> package file ready

cube/generic_networks/character_embeddings.py, cube/generic_networks/lemmatizers.py, cube/generic_networks/parsers.py, cube/generic_networks/taggers.py, cube/generic_networks/token_expanders.py, cube/generic_networks/tokenizers.py, cube/generic_networks/translators.py, cube/generic_networks/wrappers.py, cube/io_utils/config.py, cube/io_utils/conll.py, cube/io_utils/embeddings.py, cube/io_utils/encodings.py, cube/io_utils/model_store.py, cube/io_utils/mt.py, cube/io_utils/trainers.py, cube/main.py, cube/misc/misc.py
Updated all expr() with update=True, and added overload fopen to handle python2 and 3 seamlessly.
=> Expr update

cube/api.py, cube/generic_networks/ner.py, cube/io_utils/config.py, cube/io_utils/cupt.py, cube/io_utils/encodings.py, cube/io_utils/trainers.py, cube/main.py, docs/blog/list.html, docs/blog/posts/3-ner/main.html
This PR refers to the integration of the Graph-Based-Decoding algorithm used for MWE and NER into the main branch of NLP-Cube.
Changes:
Added ner.py which contains the model and algorithm
Added Trainer for NER
Modified command line arguments to include training for NER
Minor update to api.py to accept pre-tokenized input in the form of CONLLU data
Updated docs to include information about results obtained on NER using the CONLL 2003 corpus.
Output of PARSEME evaluator on the NER testset
```
* MWE-based: P=5369/5849=0.9179 R=5369/5648=0.9506 F=0.9340
* Tok-based: P=7884/8465=0.9314 R=7884/8112=0.9719 F=0.9512
* LOC: MWE-proportion: gold=1668/5648=30% pred=1580/5849=27%
* LOC: MWE-based: P=1472/1580=0.9316 R=1472/1668=0.8825 F=0.9064
* LOC: Tok-based: P=1675/1797=0.9321 R=1675/1925=0.8701 …
```
=> Dev.gp ner working

scripts/package_ud_models.py
script to create zip models from folders containing already trained models (UD-specific)
=> script to package zip models

README.md
=> Dumitrescustefan patch 1

examples/simple_example.ipynb
=> Re-added the simple example

cube/api.py, cube/main.py
- Added support for random seed in main.py and api.py
- In api.py added parameters in the cube.init() function for memory allocation, autobatching and gpu usage flags.
Closes #66 and #67 .
=> Random seed parameter & Dynet config parameters in API

README.md
Corrected the URL for local example referred **locally install NLP-Cube**
**
**
=> Corrected url for example

.gitignore, README.md, cube/io_utils/model_store.py, cube/main.py, scripts/result_mdtable_generator.py, scripts/test_all_models.py
Added scripts that test all available online models and generate an md table with the results.
=> Model performance script

scripts/package_ud_models.py, tests/api_tests.py
Change in link from fb's wiki embeddings
=> Change in link from fb's wiki embeddings

docker/Dockerfile, scripts/build_docker.sh, scripts/run_docker.sh
This PR introduces a docker image that installs MKL accelerated DyNET, clone the master branch of NLPCube and starts a Jupyter Notebook.
It is useful for building models on any OS, given that the user mounts a data-folder, whenever starting the Docker image.
=> Dockerfile working

README.md, docs/blog/list.html, docs/blog/posts/1-gbd/main.html, docs/blog/posts/2-ud/main.html, setup.py
Fixed a few typos in docs and setup.py
=> Fixed typos

docs/blog/posts/2-ud/main.html
=> Fix typo and passed through grammarly

README.md
=> Stars Badge Added
